FormsApp/FormsApp/Models/FormCon.cs
namespace FormsApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Linq;

    public class FormCon : DbContext
    {
        public FormCon()
            : base("name=FormCon")
        {
        }
        public virtual DbSet<FormItem> FormItem { get; set; }
    }
}

FormsApp/FormsApp/Models/FormItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FormsApp.Models
{
    public class FormItem
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Tender { get; set; }
        public DateTime RegisterDate { get; set; }
        public string Email { get; set; }
    }
}

FormsApp/FormsApp/Models/ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FormsApp.Models
{
    public class ViewModel
    {
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Tender { get; set; }
        public string Email { get; set; }
        public DateTime RegisterDate { get; set; }
        public virtual int first { get; set; }
        public virtual int second { get; set; }
        public virtual int top { get; set; }
    }
}

FormsApp/FormsApp/Controllers/FController.cs
using FormsApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormsApp.Controllers
{
    public class FController : Controller
    {
        // R: registry
        public ActionResult R()
        {
            return View();
        }

        [HttpPost]
        public ActionResult R(ViewModel model)
        {
            if(model.first + model.second == model.top)
            {
                using (FormCon con = new FormCon())
                {
                    FormItem item = new FormItem();
                    item.Name = model.Name;
                    item.Phone = model.Phone;
                    item.RegisterDate = DateTime.Now;
                    //item.Tender = model.Tender;
                    item.Email = model.Email;
                    con.FormItem.Add(item);
                    con.SaveChanges();
                }

                TempData["AlertMessage"] = "Teşekkür Ederiz, Etkinliklerde Görüşmek üzere :)";
            }
            else
            {
                TempData["AlertMessage"] = "Toplama Yanlış!";

            }
            return View();
        }

        // L: List
        public ActionResult L()
        {
            List<FormItem> list = new List<FormItem>();

            using (FormCon con = new FormCon())
            {
                list = con.FormItem.ToList();
            }
            return View(list);
        }
    }
}

FormsApp/FormsApp/Views/F/L.cshtml
@model List<FormsApp.Models.FormItem>
@{
    Layout = null;
}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="~/Content/Css/table.css" rel="stylesheet" />

<!-- TABLE -->
<table class="table table-action">
    <thead>
        <tr>
            <th><b>İsim - Soy İsim</b></th>
            <th><b>E-Mail</b></th>
            <th><b>Tarih</b></th>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name.ToUpper()</td>
                    <td>@item.Email</td>
                    <td>@item.RegisterDate.ToString("dd/MM/yyyy")</td>
                </tr>
            }
        }
    </tbody>
</table>
<!-- END TABLE -->

FormsApp/FormsApp/Views/F/R.cshtml
@{
    Layout = null;
    var message = TempData["AlertMessage"] ?? string.Empty;
}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="~/Content/Css/form.css" rel="stylesheet" />


<div class="container">
    <form id="contact" action="" method="post">
        @using (Html.BeginForm("R", "F"))
        {
            <center>
                <h2 style="color: #F96;">KodFest Etkinlikleri Mail Litesi</h2>

                <p style="font-size:10.5px;"><b>KodFest etkinliklerinden haberdar olmak için mail listeine kayıt olun.</b></p>
                <a style="font-size: 15px;" href="http://kodfest.com/" target="_blank"><p>kodfest.com</p></a>
                <a style="font-size: 15px;" href="https://twitter.com/kodfest" target="_blank"><p>twitter.com/kodfest</p></a>
                <br />
            </center>
            <fieldset>
                <input placeholder="İsim Soyisim" type="text" tabindex="1" required name="Name">
            </fieldset>
            <fieldset>
                <input placeholder="Telefon Numaranız" type="tel" tabindex="3" required name="Phone">
            </fieldset>
            <fieldset>
                <input placeholder="Mail Adresiniz" type="email" tabindex="5" required name="Email">
            </fieldset>
            @*<fieldset>
                <textarea placeholder="Öneriler..." tabindex="5" name="Tender"></textarea>
            </fieldset>*@

                Random r = new Random();
                int first = r.Next(1, 9);
                int second = r.Next(1, 9);
            
            <input type="hidden" value="@first" name="first"/>
            <input type="hidden" value="@second" name="second" />

                <fieldset>
                    <input placeholder="@first + @second = ?" type="text" tabindex="7" required name="top">
                </fieldset>

            <fieldset>
                <button name="submit" type="submit" id="contact-submit" data-submit="...Gönderiliyor">Kayıt Ol</button>
            </fieldset>
            
        }
    </form>
</div>

<script type="text/javascript">
    var message = '@message';
    if(message)
        alert(message);
</script>